// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: analytics.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const analyticsMRR = `-- name: AnalyticsMRR :one
SELECT COALESCE(SUM(
  CASE p.interval_unit
    WHEN 'day'   THEN p.amount_minor * 30 / GREATEST(p.interval_count, 1)
    WHEN 'week'  THEN p.amount_minor * 4  / GREATEST(p.interval_count, 1)
    WHEN 'month' THEN p.amount_minor      / GREATEST(p.interval_count, 1)
    WHEN 'year'  THEN p.amount_minor      / (12 * GREATEST(p.interval_count, 1))
    ELSE p.amount_minor
  END * s.quantity), 0)::bigint AS mrr_minor
FROM subscriptions s
JOIN prices p ON p.id = s.price_id
WHERE s.merchant_id = $1 AND s.mode = $2 AND s.status IN ('active', 'trialing')
`

type AnalyticsMRRParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
}

func (q *Queries) AnalyticsMRR(ctx context.Context, arg AnalyticsMRRParams) (int64, error) {
	row := q.db.QueryRow(ctx, analyticsMRR, arg.MerchantID, arg.Mode)
	var mrr_minor int64
	err := row.Scan(&mrr_minor)
	return mrr_minor, err
}

const countCustomers = `-- name: CountCustomers :one
SELECT COUNT(*)::bigint AS count
FROM customers WHERE merchant_id = $1 AND mode = $2
`

type CountCustomersParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
}

func (q *Queries) CountCustomers(ctx context.Context, arg CountCustomersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCustomers, arg.MerchantID, arg.Mode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const revenueByDay = `-- name: RevenueByDay :many
SELECT (date_trunc('day', created_at))::date AS day,
       COALESCE(SUM(amount_minor), 0)::bigint AS amount_minor
FROM transactions
WHERE merchant_id = $1 AND mode = $2 AND status = 'succeeded'
  AND created_at >= now() - interval '30 days'
GROUP BY 1
ORDER BY 1
`

type RevenueByDayParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
}

type RevenueByDayRow struct {
	Day         pgtype.Date `json:"day"`
	AmountMinor int64       `json:"amount_minor"`
}

func (q *Queries) RevenueByDay(ctx context.Context, arg RevenueByDayParams) ([]RevenueByDayRow, error) {
	rows, err := q.db.Query(ctx, revenueByDay, arg.MerchantID, arg.Mode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RevenueByDayRow{}
	for rows.Next() {
		var i RevenueByDayRow
		if err := rows.Scan(&i.Day, &i.AmountMinor); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscriptionStatusBreakdown = `-- name: SubscriptionStatusBreakdown :many
SELECT status, COUNT(*)::bigint AS count
FROM subscriptions
WHERE merchant_id = $1 AND mode = $2
GROUP BY status
ORDER BY count DESC
`

type SubscriptionStatusBreakdownParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
}

type SubscriptionStatusBreakdownRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) SubscriptionStatusBreakdown(ctx context.Context, arg SubscriptionStatusBreakdownParams) ([]SubscriptionStatusBreakdownRow, error) {
	rows, err := q.db.Query(ctx, subscriptionStatusBreakdown, arg.MerchantID, arg.Mode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionStatusBreakdownRow{}
	for rows.Next() {
		var i SubscriptionStatusBreakdownRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscriptionsByDay = `-- name: SubscriptionsByDay :many
SELECT (date_trunc('day', created_at))::date AS day,
       COUNT(*)::bigint AS count
FROM subscriptions
WHERE merchant_id = $1 AND mode = $2
  AND created_at >= now() - interval '30 days'
GROUP BY 1
ORDER BY 1
`

type SubscriptionsByDayParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
}

type SubscriptionsByDayRow struct {
	Day   pgtype.Date `json:"day"`
	Count int64       `json:"count"`
}

func (q *Queries) SubscriptionsByDay(ctx context.Context, arg SubscriptionsByDayParams) ([]SubscriptionsByDayRow, error) {
	rows, err := q.db.Query(ctx, subscriptionsByDay, arg.MerchantID, arg.Mode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SubscriptionsByDayRow{}
	for rows.Next() {
		var i SubscriptionsByDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalRevenue = `-- name: TotalRevenue :one
SELECT COALESCE(SUM(amount_minor), 0)::bigint AS total
FROM transactions WHERE merchant_id = $1 AND mode = $2 AND status = 'succeeded'
`

type TotalRevenueParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
}

func (q *Queries) TotalRevenue(ctx context.Context, arg TotalRevenueParams) (int64, error) {
	row := q.db.QueryRow(ctx, totalRevenue, arg.MerchantID, arg.Mode)
	var total int64
	err := row.Scan(&total)
	return total, err
}
