// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (merchant_id, prefix, key_hash, scopes)
VALUES ($1, $2, $3, $4)
RETURNING id, merchant_id, prefix, key_hash, scopes, last_used_at, revoked_at, created_at
`

type CreateAPIKeyParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Prefix     string    `json:"prefix"`
	KeyHash    string    `json:"key_hash"`
	Scopes     []string  `json:"scopes"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.MerchantID,
		arg.Prefix,
		arg.KeyHash,
		arg.Scopes,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Prefix,
		&i.KeyHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createGatewayAccount = `-- name: CreateGatewayAccount :one
INSERT INTO gateway_accounts (merchant_id, provider, account_ref, encrypted_credentials)
VALUES ($1, $2, $3, $4)
RETURNING id, merchant_id, provider, account_ref, encrypted_credentials, status, created_at, mode, publishable_key
`

type CreateGatewayAccountParams struct {
	MerchantID           uuid.UUID   `json:"merchant_id"`
	Provider             string      `json:"provider"`
	AccountRef           pgtype.Text `json:"account_ref"`
	EncryptedCredentials []byte      `json:"encrypted_credentials"`
}

func (q *Queries) CreateGatewayAccount(ctx context.Context, arg CreateGatewayAccountParams) (GatewayAccount, error) {
	row := q.db.QueryRow(ctx, createGatewayAccount,
		arg.MerchantID,
		arg.Provider,
		arg.AccountRef,
		arg.EncryptedCredentials,
	)
	var i GatewayAccount
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Provider,
		&i.AccountRef,
		&i.EncryptedCredentials,
		&i.Status,
		&i.CreatedAt,
		&i.Mode,
		&i.PublishableKey,
	)
	return i, err
}

const createMerchantUser = `-- name: CreateMerchantUser :one
INSERT INTO merchant_users (merchant_id, email, password_hash, role)
VALUES ($1, $2, $3, $4)
RETURNING id, merchant_id, email, password_hash, role, created_at
`

type CreateMerchantUserParams struct {
	MerchantID   uuid.UUID `json:"merchant_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
}

func (q *Queries) CreateMerchantUser(ctx context.Context, arg CreateMerchantUserParams) (MerchantUser, error) {
	row := q.db.QueryRow(ctx, createMerchantUser,
		arg.MerchantID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i MerchantUser
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT id, merchant_id, prefix, key_hash, scopes, last_used_at, revoked_at, created_at FROM api_keys
WHERE prefix = $1 AND revoked_at IS NULL
`

func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, prefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Prefix,
		&i.KeyHash,
		&i.Scopes,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMerchantUserByEmail = `-- name: GetMerchantUserByEmail :one
SELECT id, merchant_id, email, password_hash, role, created_at FROM merchant_users
WHERE email = $1
`

func (q *Queries) GetMerchantUserByEmail(ctx context.Context, email string) (MerchantUser, error) {
	row := q.db.QueryRow(ctx, getMerchantUserByEmail, email)
	var i MerchantUser
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysByMerchant = `-- name: ListAPIKeysByMerchant :many
SELECT id, merchant_id, prefix, scopes, last_used_at, revoked_at, created_at
FROM api_keys
WHERE merchant_id = $1
ORDER BY created_at DESC
`

type ListAPIKeysByMerchantRow struct {
	ID         uuid.UUID          `json:"id"`
	MerchantID uuid.UUID          `json:"merchant_id"`
	Prefix     string             `json:"prefix"`
	Scopes     []string           `json:"scopes"`
	LastUsedAt *time.Time         `json:"last_used_at"`
	RevokedAt  *time.Time         `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAPIKeysByMerchant(ctx context.Context, merchantID uuid.UUID) ([]ListAPIKeysByMerchantRow, error) {
	rows, err := q.db.Query(ctx, listAPIKeysByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysByMerchantRow{}
	for rows.Next() {
		var i ListAPIKeysByMerchantRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Prefix,
			&i.Scopes,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys
SET revoked_at = now()
WHERE id = $1 AND merchant_id = $2
`

type RevokeAPIKeyParams struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, arg.ID, arg.MerchantID)
	return err
}

const touchAPIKey = `-- name: TouchAPIKey :exec
UPDATE api_keys
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) TouchAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKey, id)
	return err
}
