// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDunningAttempt = `-- name: CreateDunningAttempt :one
INSERT INTO dunning_attempts (merchant_id, mode, invoice_id, attempt_no, scheduled_at, attempted_at, result)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, merchant_id, invoice_id, attempt_no, scheduled_at, attempted_at, result, created_at, mode
`

type CreateDunningAttemptParams struct {
	MerchantID  uuid.UUID          `json:"merchant_id"`
	Mode        string             `json:"mode"`
	InvoiceID   uuid.UUID          `json:"invoice_id"`
	AttemptNo   int32              `json:"attempt_no"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	AttemptedAt *time.Time         `json:"attempted_at"`
	Result      pgtype.Text        `json:"result"`
}

func (q *Queries) CreateDunningAttempt(ctx context.Context, arg CreateDunningAttemptParams) (DunningAttempt, error) {
	row := q.db.QueryRow(ctx, createDunningAttempt,
		arg.MerchantID,
		arg.Mode,
		arg.InvoiceID,
		arg.AttemptNo,
		arg.ScheduledAt,
		arg.AttemptedAt,
		arg.Result,
	)
	var i DunningAttempt
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.InvoiceID,
		&i.AttemptNo,
		&i.ScheduledAt,
		&i.AttemptedAt,
		&i.Result,
		&i.CreatedAt,
		&i.Mode,
	)
	return i, err
}

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    merchant_id, mode, customer_id, subscription_id, status, currency,
    subtotal_minor, discount_minor, tax_minor, total_minor,
    period_start, period_end, issued_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, merchant_id, customer_id, subscription_id, status, currency, subtotal_minor, discount_minor, tax_minor, total_minor, period_start, period_end, issued_at, paid_at, created_at, mode
`

type CreateInvoiceParams struct {
	MerchantID     uuid.UUID   `json:"merchant_id"`
	Mode           string      `json:"mode"`
	CustomerID     uuid.UUID   `json:"customer_id"`
	SubscriptionID pgtype.UUID `json:"subscription_id"`
	Status         string      `json:"status"`
	Currency       string      `json:"currency"`
	SubtotalMinor  int64       `json:"subtotal_minor"`
	DiscountMinor  int64       `json:"discount_minor"`
	TaxMinor       int64       `json:"tax_minor"`
	TotalMinor     int64       `json:"total_minor"`
	PeriodStart    *time.Time  `json:"period_start"`
	PeriodEnd      *time.Time  `json:"period_end"`
	IssuedAt       *time.Time  `json:"issued_at"`
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.MerchantID,
		arg.Mode,
		arg.CustomerID,
		arg.SubscriptionID,
		arg.Status,
		arg.Currency,
		arg.SubtotalMinor,
		arg.DiscountMinor,
		arg.TaxMinor,
		arg.TotalMinor,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.IssuedAt,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.Status,
		&i.Currency,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TaxMinor,
		&i.TotalMinor,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IssuedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.Mode,
	)
	return i, err
}

const createInvoiceLineItem = `-- name: CreateInvoiceLineItem :one
INSERT INTO invoice_line_items (invoice_id, description, quantity, unit_amount_minor, amount_minor)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, invoice_id, description, quantity, unit_amount_minor, amount_minor
`

type CreateInvoiceLineItemParams struct {
	InvoiceID       uuid.UUID `json:"invoice_id"`
	Description     string    `json:"description"`
	Quantity        int32     `json:"quantity"`
	UnitAmountMinor int64     `json:"unit_amount_minor"`
	AmountMinor     int64     `json:"amount_minor"`
}

func (q *Queries) CreateInvoiceLineItem(ctx context.Context, arg CreateInvoiceLineItemParams) (InvoiceLineItem, error) {
	row := q.db.QueryRow(ctx, createInvoiceLineItem,
		arg.InvoiceID,
		arg.Description,
		arg.Quantity,
		arg.UnitAmountMinor,
		arg.AmountMinor,
	)
	var i InvoiceLineItem
	err := row.Scan(
		&i.ID,
		&i.InvoiceID,
		&i.Description,
		&i.Quantity,
		&i.UnitAmountMinor,
		&i.AmountMinor,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    merchant_id, mode, invoice_id, gateway_txn_ref, status,
    amount_minor, currency, failure_reason, idempotency_key
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, merchant_id, invoice_id, gateway_txn_ref, status, amount_minor, currency, failure_reason, idempotency_key, created_at, mode
`

type CreateTransactionParams struct {
	MerchantID     uuid.UUID   `json:"merchant_id"`
	Mode           string      `json:"mode"`
	InvoiceID      pgtype.UUID `json:"invoice_id"`
	GatewayTxnRef  pgtype.Text `json:"gateway_txn_ref"`
	Status         string      `json:"status"`
	AmountMinor    int64       `json:"amount_minor"`
	Currency       string      `json:"currency"`
	FailureReason  pgtype.Text `json:"failure_reason"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.MerchantID,
		arg.Mode,
		arg.InvoiceID,
		arg.GatewayTxnRef,
		arg.Status,
		arg.AmountMinor,
		arg.Currency,
		arg.FailureReason,
		arg.IdempotencyKey,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.InvoiceID,
		&i.GatewayTxnRef,
		&i.Status,
		&i.AmountMinor,
		&i.Currency,
		&i.FailureReason,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.Mode,
	)
	return i, err
}

const deleteGatewayAccount = `-- name: DeleteGatewayAccount :execrows
DELETE FROM gateway_accounts
WHERE merchant_id = $1 AND mode = $2 AND provider = $3
`

type DeleteGatewayAccountParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
	Provider   string    `json:"provider"`
}

// Disconnect a gateway for a merchant + mode (removes the stored credentials).
func (q *Queries) DeleteGatewayAccount(ctx context.Context, arg DeleteGatewayAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteGatewayAccount, arg.MerchantID, arg.Mode, arg.Provider)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getGatewayAccount = `-- name: GetGatewayAccount :one
SELECT id, merchant_id, provider, account_ref, encrypted_credentials, status, created_at, mode FROM gateway_accounts
WHERE merchant_id = $1 AND mode = $2 AND provider = $3
`

type GetGatewayAccountParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
	Provider   string    `json:"provider"`
}

func (q *Queries) GetGatewayAccount(ctx context.Context, arg GetGatewayAccountParams) (GatewayAccount, error) {
	row := q.db.QueryRow(ctx, getGatewayAccount, arg.MerchantID, arg.Mode, arg.Provider)
	var i GatewayAccount
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Provider,
		&i.AccountRef,
		&i.EncryptedCredentials,
		&i.Status,
		&i.CreatedAt,
		&i.Mode,
	)
	return i, err
}

const getPrimaryGatewayAccount = `-- name: GetPrimaryGatewayAccount :one
SELECT id, merchant_id, provider, account_ref, encrypted_credentials, status, created_at, mode FROM gateway_accounts
WHERE merchant_id = $1 AND mode = $2 AND status = 'connected'
ORDER BY created_at DESC
LIMIT 1
`

type GetPrimaryGatewayAccountParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
}

// The merchant's active gateway used for charging, for a given mode.
func (q *Queries) GetPrimaryGatewayAccount(ctx context.Context, arg GetPrimaryGatewayAccountParams) (GatewayAccount, error) {
	row := q.db.QueryRow(ctx, getPrimaryGatewayAccount, arg.MerchantID, arg.Mode)
	var i GatewayAccount
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Provider,
		&i.AccountRef,
		&i.EncryptedCredentials,
		&i.Status,
		&i.CreatedAt,
		&i.Mode,
	)
	return i, err
}

const listGatewayAccountsByMerchant = `-- name: ListGatewayAccountsByMerchant :many
SELECT id, merchant_id, mode, provider, account_ref, status, created_at
FROM gateway_accounts
WHERE merchant_id = $1 AND mode = $2
ORDER BY created_at DESC
`

type ListGatewayAccountsByMerchantParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
}

type ListGatewayAccountsByMerchantRow struct {
	ID         uuid.UUID          `json:"id"`
	MerchantID uuid.UUID          `json:"merchant_id"`
	Mode       string             `json:"mode"`
	Provider   string             `json:"provider"`
	AccountRef pgtype.Text        `json:"account_ref"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListGatewayAccountsByMerchant(ctx context.Context, arg ListGatewayAccountsByMerchantParams) ([]ListGatewayAccountsByMerchantRow, error) {
	rows, err := q.db.Query(ctx, listGatewayAccountsByMerchant, arg.MerchantID, arg.Mode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGatewayAccountsByMerchantRow{}
	for rows.Next() {
		var i ListGatewayAccountsByMerchantRow
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Mode,
			&i.Provider,
			&i.AccountRef,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvoicesByMerchant = `-- name: ListInvoicesByMerchant :many
SELECT id, merchant_id, customer_id, subscription_id, status, currency, subtotal_minor, discount_minor, tax_minor, total_minor, period_start, period_end, issued_at, paid_at, created_at, mode FROM invoices
WHERE merchant_id = $1 AND mode = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListInvoicesByMerchantParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListInvoicesByMerchant(ctx context.Context, arg ListInvoicesByMerchantParams) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByMerchant,
		arg.MerchantID,
		arg.Mode,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.CustomerID,
			&i.SubscriptionID,
			&i.Status,
			&i.Currency,
			&i.SubtotalMinor,
			&i.DiscountMinor,
			&i.TaxMinor,
			&i.TotalMinor,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.IssuedAt,
			&i.PaidAt,
			&i.CreatedAt,
			&i.Mode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByMerchant = `-- name: ListTransactionsByMerchant :many
SELECT id, merchant_id, invoice_id, gateway_txn_ref, status, amount_minor, currency, failure_reason, idempotency_key, created_at, mode FROM transactions
WHERE merchant_id = $1 AND mode = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListTransactionsByMerchantParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListTransactionsByMerchant(ctx context.Context, arg ListTransactionsByMerchantParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByMerchant,
		arg.MerchantID,
		arg.Mode,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.InvoiceID,
			&i.GatewayTxnRef,
			&i.Status,
			&i.AmountMinor,
			&i.Currency,
			&i.FailureReason,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.Mode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markInvoicePaid = `-- name: MarkInvoicePaid :one
UPDATE invoices
SET status = 'paid', paid_at = now()
WHERE id = $1
RETURNING id, merchant_id, customer_id, subscription_id, status, currency, subtotal_minor, discount_minor, tax_minor, total_minor, period_start, period_end, issued_at, paid_at, created_at, mode
`

func (q *Queries) MarkInvoicePaid(ctx context.Context, id uuid.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, markInvoicePaid, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.Status,
		&i.Currency,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TaxMinor,
		&i.TotalMinor,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IssuedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.Mode,
	)
	return i, err
}

const markInvoiceStatus = `-- name: MarkInvoiceStatus :one
UPDATE invoices
SET status = $2
WHERE id = $1
RETURNING id, merchant_id, customer_id, subscription_id, status, currency, subtotal_minor, discount_minor, tax_minor, total_minor, period_start, period_end, issued_at, paid_at, created_at, mode
`

type MarkInvoiceStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) MarkInvoiceStatus(ctx context.Context, arg MarkInvoiceStatusParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, markInvoiceStatus, arg.ID, arg.Status)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.Status,
		&i.Currency,
		&i.SubtotalMinor,
		&i.DiscountMinor,
		&i.TaxMinor,
		&i.TotalMinor,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.IssuedAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.Mode,
	)
	return i, err
}

const upsertGatewayAccount = `-- name: UpsertGatewayAccount :one
INSERT INTO gateway_accounts (merchant_id, mode, provider, account_ref, encrypted_credentials, status)
VALUES ($1, $2, $3, $4, $5, 'connected')
ON CONFLICT (merchant_id, mode, provider)
DO UPDATE SET account_ref = EXCLUDED.account_ref,
              encrypted_credentials = EXCLUDED.encrypted_credentials,
              status = 'connected'
RETURNING id, merchant_id, mode, provider, account_ref, status, created_at
`

type UpsertGatewayAccountParams struct {
	MerchantID           uuid.UUID   `json:"merchant_id"`
	Mode                 string      `json:"mode"`
	Provider             string      `json:"provider"`
	AccountRef           pgtype.Text `json:"account_ref"`
	EncryptedCredentials []byte      `json:"encrypted_credentials"`
}

type UpsertGatewayAccountRow struct {
	ID         uuid.UUID          `json:"id"`
	MerchantID uuid.UUID          `json:"merchant_id"`
	Mode       string             `json:"mode"`
	Provider   string             `json:"provider"`
	AccountRef pgtype.Text        `json:"account_ref"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertGatewayAccount(ctx context.Context, arg UpsertGatewayAccountParams) (UpsertGatewayAccountRow, error) {
	row := q.db.QueryRow(ctx, upsertGatewayAccount,
		arg.MerchantID,
		arg.Mode,
		arg.Provider,
		arg.AccountRef,
		arg.EncryptedCredentials,
	)
	var i UpsertGatewayAccountRow
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Mode,
		&i.Provider,
		&i.AccountRef,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
