// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPrice = `-- name: CreatePrice :one
INSERT INTO prices (
    merchant_id, product_id, nickname, amount_minor, currency,
    interval_unit, interval_count, trial_days
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, merchant_id, product_id, nickname, amount_minor, currency, interval_unit, interval_count, trial_days, status, created_at
`

type CreatePriceParams struct {
	MerchantID    uuid.UUID   `json:"merchant_id"`
	ProductID     uuid.UUID   `json:"product_id"`
	Nickname      pgtype.Text `json:"nickname"`
	AmountMinor   int64       `json:"amount_minor"`
	Currency      string      `json:"currency"`
	IntervalUnit  string      `json:"interval_unit"`
	IntervalCount int32       `json:"interval_count"`
	TrialDays     int32       `json:"trial_days"`
}

func (q *Queries) CreatePrice(ctx context.Context, arg CreatePriceParams) (Price, error) {
	row := q.db.QueryRow(ctx, createPrice,
		arg.MerchantID,
		arg.ProductID,
		arg.Nickname,
		arg.AmountMinor,
		arg.Currency,
		arg.IntervalUnit,
		arg.IntervalCount,
		arg.TrialDays,
	)
	var i Price
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ProductID,
		&i.Nickname,
		&i.AmountMinor,
		&i.Currency,
		&i.IntervalUnit,
		&i.IntervalCount,
		&i.TrialDays,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (merchant_id, name)
VALUES ($1, $2)
RETURNING id, merchant_id, name, status, created_at
`

type CreateProductParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Name       string    `json:"name"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct, arg.MerchantID, arg.Name)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPrice = `-- name: GetPrice :one
SELECT id, merchant_id, product_id, nickname, amount_minor, currency, interval_unit, interval_count, trial_days, status, created_at FROM prices
WHERE id = $1 AND merchant_id = $2
`

type GetPriceParams struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

func (q *Queries) GetPrice(ctx context.Context, arg GetPriceParams) (Price, error) {
	row := q.db.QueryRow(ctx, getPrice, arg.ID, arg.MerchantID)
	var i Price
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.ProductID,
		&i.Nickname,
		&i.AmountMinor,
		&i.Currency,
		&i.IntervalUnit,
		&i.IntervalCount,
		&i.TrialDays,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listPricesByMerchant = `-- name: ListPricesByMerchant :many
SELECT id, merchant_id, product_id, nickname, amount_minor, currency, interval_unit, interval_count, trial_days, status, created_at FROM prices
WHERE merchant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPricesByMerchant(ctx context.Context, merchantID uuid.UUID) ([]Price, error) {
	rows, err := q.db.Query(ctx, listPricesByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Price{}
	for rows.Next() {
		var i Price
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.ProductID,
			&i.Nickname,
			&i.AmountMinor,
			&i.Currency,
			&i.IntervalUnit,
			&i.IntervalCount,
			&i.TrialDays,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByMerchant = `-- name: ListProductsByMerchant :many
SELECT id, merchant_id, name, status, created_at FROM products
WHERE merchant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProductsByMerchant(ctx context.Context, merchantID uuid.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
