// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkout.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeCheckoutSession = `-- name: CompleteCheckoutSession :one
UPDATE checkout_sessions
SET status = 'completed',
    customer_id = $2,
    subscription_id = $3,
    completed_at = now()
WHERE id = $1
RETURNING id, merchant_id, price_id, quantity, status, customer_email, success_url, cancel_url, customer_id, subscription_id, expires_at, completed_at, created_at, mode
`

type CompleteCheckoutSessionParams struct {
	ID             uuid.UUID   `json:"id"`
	CustomerID     pgtype.UUID `json:"customer_id"`
	SubscriptionID pgtype.UUID `json:"subscription_id"`
}

func (q *Queries) CompleteCheckoutSession(ctx context.Context, arg CompleteCheckoutSessionParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, completeCheckoutSession, arg.ID, arg.CustomerID, arg.SubscriptionID)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PriceID,
		&i.Quantity,
		&i.Status,
		&i.CustomerEmail,
		&i.SuccessUrl,
		&i.CancelUrl,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.Mode,
	)
	return i, err
}

const createCheckoutSession = `-- name: CreateCheckoutSession :one
INSERT INTO checkout_sessions (
    merchant_id, mode, price_id, quantity, customer_email, success_url, cancel_url, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, merchant_id, price_id, quantity, status, customer_email, success_url, cancel_url, customer_id, subscription_id, expires_at, completed_at, created_at, mode
`

type CreateCheckoutSessionParams struct {
	MerchantID    uuid.UUID          `json:"merchant_id"`
	Mode          string             `json:"mode"`
	PriceID       uuid.UUID          `json:"price_id"`
	Quantity      int32              `json:"quantity"`
	CustomerEmail pgtype.Text        `json:"customer_email"`
	SuccessUrl    string             `json:"success_url"`
	CancelUrl     pgtype.Text        `json:"cancel_url"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateCheckoutSession(ctx context.Context, arg CreateCheckoutSessionParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, createCheckoutSession,
		arg.MerchantID,
		arg.Mode,
		arg.PriceID,
		arg.Quantity,
		arg.CustomerEmail,
		arg.SuccessUrl,
		arg.CancelUrl,
		arg.ExpiresAt,
	)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PriceID,
		&i.Quantity,
		&i.Status,
		&i.CustomerEmail,
		&i.SuccessUrl,
		&i.CancelUrl,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.Mode,
	)
	return i, err
}

const getCheckoutSession = `-- name: GetCheckoutSession :one
SELECT id, merchant_id, price_id, quantity, status, customer_email, success_url, cancel_url, customer_id, subscription_id, expires_at, completed_at, created_at, mode FROM checkout_sessions
WHERE id = $1
`

func (q *Queries) GetCheckoutSession(ctx context.Context, id uuid.UUID) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, getCheckoutSession, id)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PriceID,
		&i.Quantity,
		&i.Status,
		&i.CustomerEmail,
		&i.SuccessUrl,
		&i.CancelUrl,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.Mode,
	)
	return i, err
}

const getCheckoutSessionDetails = `-- name: GetCheckoutSessionDetails :one
SELECT
    cs.id, cs.status, cs.quantity, cs.customer_email, cs.success_url, cs.cancel_url, cs.expires_at,
    m.name AS merchant_name,
    p.id AS price_id, p.amount_minor, p.currency, p.interval_unit, p.interval_count, p.trial_days,
    pr.name AS product_name
FROM checkout_sessions cs
JOIN merchants m ON m.id = cs.merchant_id
JOIN prices p ON p.id = cs.price_id
JOIN products pr ON pr.id = p.product_id
WHERE cs.id = $1
`

type GetCheckoutSessionDetailsRow struct {
	ID            uuid.UUID          `json:"id"`
	Status        string             `json:"status"`
	Quantity      int32              `json:"quantity"`
	CustomerEmail pgtype.Text        `json:"customer_email"`
	SuccessUrl    string             `json:"success_url"`
	CancelUrl     pgtype.Text        `json:"cancel_url"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	MerchantName  string             `json:"merchant_name"`
	PriceID       uuid.UUID          `json:"price_id"`
	AmountMinor   int64              `json:"amount_minor"`
	Currency      string             `json:"currency"`
	IntervalUnit  string             `json:"interval_unit"`
	IntervalCount int32              `json:"interval_count"`
	TrialDays     int32              `json:"trial_days"`
	ProductName   string             `json:"product_name"`
}

// Joined view for the public hosted page: session + plan + merchant + product.
func (q *Queries) GetCheckoutSessionDetails(ctx context.Context, id uuid.UUID) (GetCheckoutSessionDetailsRow, error) {
	row := q.db.QueryRow(ctx, getCheckoutSessionDetails, id)
	var i GetCheckoutSessionDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Quantity,
		&i.CustomerEmail,
		&i.SuccessUrl,
		&i.CancelUrl,
		&i.ExpiresAt,
		&i.MerchantName,
		&i.PriceID,
		&i.AmountMinor,
		&i.Currency,
		&i.IntervalUnit,
		&i.IntervalCount,
		&i.TrialDays,
		&i.ProductName,
	)
	return i, err
}
