// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: checkout.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkoutVisitsByCountry = `-- name: CheckoutVisitsByCountry :many
SELECT COALESCE(NULLIF(country, ''), 'Unknown') AS country,
       COUNT(*)::bigint AS count
FROM checkout_visits
WHERE merchant_id = $1 AND mode = $2 AND created_at >= now() - interval '30 days'
GROUP BY 1
ORDER BY count DESC
LIMIT 10
`

type CheckoutVisitsByCountryParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
}

type CheckoutVisitsByCountryRow struct {
	Country interface{} `json:"country"`
	Count   int64       `json:"count"`
}

func (q *Queries) CheckoutVisitsByCountry(ctx context.Context, arg CheckoutVisitsByCountryParams) ([]CheckoutVisitsByCountryRow, error) {
	rows, err := q.db.Query(ctx, checkoutVisitsByCountry, arg.MerchantID, arg.Mode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckoutVisitsByCountryRow{}
	for rows.Next() {
		var i CheckoutVisitsByCountryRow
		if err := rows.Scan(&i.Country, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const checkoutVisitsByDay = `-- name: CheckoutVisitsByDay :many
SELECT (date_trunc('day', created_at))::date AS day,
       COUNT(*)::bigint AS count
FROM checkout_visits
WHERE merchant_id = $1 AND mode = $2 AND created_at >= now() - interval '30 days'
GROUP BY 1
ORDER BY 1
`

type CheckoutVisitsByDayParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
}

type CheckoutVisitsByDayRow struct {
	Day   pgtype.Date `json:"day"`
	Count int64       `json:"count"`
}

func (q *Queries) CheckoutVisitsByDay(ctx context.Context, arg CheckoutVisitsByDayParams) ([]CheckoutVisitsByDayRow, error) {
	rows, err := q.db.Query(ctx, checkoutVisitsByDay, arg.MerchantID, arg.Mode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CheckoutVisitsByDayRow{}
	for rows.Next() {
		var i CheckoutVisitsByDayRow
		if err := rows.Scan(&i.Day, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeCheckoutSession = `-- name: CompleteCheckoutSession :one
UPDATE checkout_sessions
SET status = 'completed',
    customer_id = $2,
    subscription_id = $3,
    completed_at = now()
WHERE id = $1
RETURNING id, merchant_id, price_id, quantity, status, customer_email, success_url, cancel_url, customer_id, subscription_id, expires_at, completed_at, created_at, mode
`

type CompleteCheckoutSessionParams struct {
	ID             uuid.UUID   `json:"id"`
	CustomerID     pgtype.UUID `json:"customer_id"`
	SubscriptionID pgtype.UUID `json:"subscription_id"`
}

func (q *Queries) CompleteCheckoutSession(ctx context.Context, arg CompleteCheckoutSessionParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, completeCheckoutSession, arg.ID, arg.CustomerID, arg.SubscriptionID)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PriceID,
		&i.Quantity,
		&i.Status,
		&i.CustomerEmail,
		&i.SuccessUrl,
		&i.CancelUrl,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.Mode,
	)
	return i, err
}

const countCheckoutVisits = `-- name: CountCheckoutVisits :one
SELECT COUNT(*)::bigint AS count
FROM checkout_visits
WHERE merchant_id = $1 AND mode = $2 AND created_at >= now() - interval '30 days'
`

type CountCheckoutVisitsParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
}

func (q *Queries) CountCheckoutVisits(ctx context.Context, arg CountCheckoutVisitsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCheckoutVisits, arg.MerchantID, arg.Mode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCompletedCheckouts = `-- name: CountCompletedCheckouts :one
SELECT COUNT(*)::bigint AS count
FROM checkout_sessions
WHERE merchant_id = $1 AND mode = $2 AND status = 'completed'
  AND created_at >= now() - interval '30 days'
`

type CountCompletedCheckoutsParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
}

func (q *Queries) CountCompletedCheckouts(ctx context.Context, arg CountCompletedCheckoutsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedCheckouts, arg.MerchantID, arg.Mode)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCheckoutSession = `-- name: CreateCheckoutSession :one
INSERT INTO checkout_sessions (
    merchant_id, mode, price_id, quantity, customer_email, success_url, cancel_url, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, merchant_id, price_id, quantity, status, customer_email, success_url, cancel_url, customer_id, subscription_id, expires_at, completed_at, created_at, mode
`

type CreateCheckoutSessionParams struct {
	MerchantID    uuid.UUID          `json:"merchant_id"`
	Mode          string             `json:"mode"`
	PriceID       uuid.UUID          `json:"price_id"`
	Quantity      int32              `json:"quantity"`
	CustomerEmail pgtype.Text        `json:"customer_email"`
	SuccessUrl    string             `json:"success_url"`
	CancelUrl     pgtype.Text        `json:"cancel_url"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateCheckoutSession(ctx context.Context, arg CreateCheckoutSessionParams) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, createCheckoutSession,
		arg.MerchantID,
		arg.Mode,
		arg.PriceID,
		arg.Quantity,
		arg.CustomerEmail,
		arg.SuccessUrl,
		arg.CancelUrl,
		arg.ExpiresAt,
	)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PriceID,
		&i.Quantity,
		&i.Status,
		&i.CustomerEmail,
		&i.SuccessUrl,
		&i.CancelUrl,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.Mode,
	)
	return i, err
}

const getCheckoutSession = `-- name: GetCheckoutSession :one
SELECT id, merchant_id, price_id, quantity, status, customer_email, success_url, cancel_url, customer_id, subscription_id, expires_at, completed_at, created_at, mode FROM checkout_sessions
WHERE id = $1
`

func (q *Queries) GetCheckoutSession(ctx context.Context, id uuid.UUID) (CheckoutSession, error) {
	row := q.db.QueryRow(ctx, getCheckoutSession, id)
	var i CheckoutSession
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.PriceID,
		&i.Quantity,
		&i.Status,
		&i.CustomerEmail,
		&i.SuccessUrl,
		&i.CancelUrl,
		&i.CustomerID,
		&i.SubscriptionID,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.Mode,
	)
	return i, err
}

const getCheckoutSessionDetails = `-- name: GetCheckoutSessionDetails :one
SELECT
    cs.id, cs.status, cs.quantity, cs.customer_email, cs.success_url, cs.cancel_url, cs.expires_at,
    m.name AS merchant_name,
    p.id AS price_id, p.amount_minor, p.currency, p.interval_unit, p.interval_count, p.trial_days,
    pr.name AS product_name
FROM checkout_sessions cs
JOIN merchants m ON m.id = cs.merchant_id
JOIN prices p ON p.id = cs.price_id
JOIN products pr ON pr.id = p.product_id
WHERE cs.id = $1
`

type GetCheckoutSessionDetailsRow struct {
	ID            uuid.UUID          `json:"id"`
	Status        string             `json:"status"`
	Quantity      int32              `json:"quantity"`
	CustomerEmail pgtype.Text        `json:"customer_email"`
	SuccessUrl    string             `json:"success_url"`
	CancelUrl     pgtype.Text        `json:"cancel_url"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	MerchantName  string             `json:"merchant_name"`
	PriceID       uuid.UUID          `json:"price_id"`
	AmountMinor   int64              `json:"amount_minor"`
	Currency      string             `json:"currency"`
	IntervalUnit  string             `json:"interval_unit"`
	IntervalCount int32              `json:"interval_count"`
	TrialDays     int32              `json:"trial_days"`
	ProductName   string             `json:"product_name"`
}

// Joined view for the public hosted page: session + plan + merchant + product.
func (q *Queries) GetCheckoutSessionDetails(ctx context.Context, id uuid.UUID) (GetCheckoutSessionDetailsRow, error) {
	row := q.db.QueryRow(ctx, getCheckoutSessionDetails, id)
	var i GetCheckoutSessionDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Quantity,
		&i.CustomerEmail,
		&i.SuccessUrl,
		&i.CancelUrl,
		&i.ExpiresAt,
		&i.MerchantName,
		&i.PriceID,
		&i.AmountMinor,
		&i.Currency,
		&i.IntervalUnit,
		&i.IntervalCount,
		&i.TrialDays,
		&i.ProductName,
	)
	return i, err
}

const insertCheckoutVisit = `-- name: InsertCheckoutVisit :exec

INSERT INTO checkout_visits (merchant_id, mode, session_id, country, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertCheckoutVisitParams struct {
	MerchantID uuid.UUID          `json:"merchant_id"`
	Mode       string             `json:"mode"`
	SessionID  pgtype.UUID        `json:"session_id"`
	Country    string             `json:"country"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// ── Hosted checkout visit analytics ────────────────────────────────
func (q *Queries) InsertCheckoutVisit(ctx context.Context, arg InsertCheckoutVisitParams) error {
	_, err := q.db.Exec(ctx, insertCheckoutVisit,
		arg.MerchantID,
		arg.Mode,
		arg.SessionID,
		arg.Country,
		arg.CreatedAt,
	)
	return err
}

const seedCheckoutSession = `-- name: SeedCheckoutSession :exec
INSERT INTO checkout_sessions (merchant_id, mode, price_id, quantity, status, success_url, expires_at, completed_at, created_at)
VALUES ($1, $2, $3, 1, 'completed', 'https://example.com/success', $4, $5, $5)
`

type SeedCheckoutSessionParams struct {
	MerchantID  uuid.UUID          `json:"merchant_id"`
	Mode        string             `json:"mode"`
	PriceID     uuid.UUID          `json:"price_id"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	CompletedAt *time.Time         `json:"completed_at"`
}

// A backdated completed checkout session (dev seeder, for conversion stats).
func (q *Queries) SeedCheckoutSession(ctx context.Context, arg SeedCheckoutSessionParams) error {
	_, err := q.db.Exec(ctx, seedCheckoutSession,
		arg.MerchantID,
		arg.Mode,
		arg.PriceID,
		arg.ExpiresAt,
		arg.CompletedAt,
	)
	return err
}
