// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coupons.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCoupon = `-- name: CreateCoupon :one
INSERT INTO coupons (merchant_id, mode, code, discount_type, value, max_redemptions, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, merchant_id, code, discount_type, value, max_redemptions, redemptions, expires_at, created_at, mode, status
`

type CreateCouponParams struct {
	MerchantID     uuid.UUID   `json:"merchant_id"`
	Mode           string      `json:"mode"`
	Code           string      `json:"code"`
	DiscountType   string      `json:"discount_type"`
	Value          int64       `json:"value"`
	MaxRedemptions pgtype.Int4 `json:"max_redemptions"`
	ExpiresAt      *time.Time  `json:"expires_at"`
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, createCoupon,
		arg.MerchantID,
		arg.Mode,
		arg.Code,
		arg.DiscountType,
		arg.Value,
		arg.MaxRedemptions,
		arg.ExpiresAt,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Code,
		&i.DiscountType,
		&i.Value,
		&i.MaxRedemptions,
		&i.Redemptions,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Mode,
		&i.Status,
	)
	return i, err
}

const deleteCoupon = `-- name: DeleteCoupon :execrows
DELETE FROM coupons
WHERE id = $1 AND merchant_id = $2
`

type DeleteCouponParams struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

// Permanently remove a coupon.
func (q *Queries) DeleteCoupon(ctx context.Context, arg DeleteCouponParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCoupon, arg.ID, arg.MerchantID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCouponByCode = `-- name: GetCouponByCode :one
SELECT id, merchant_id, code, discount_type, value, max_redemptions, redemptions, expires_at, created_at, mode, status FROM coupons
WHERE merchant_id = $1 AND mode = $2 AND code = $3
`

type GetCouponByCodeParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
	Code       string    `json:"code"`
}

func (q *Queries) GetCouponByCode(ctx context.Context, arg GetCouponByCodeParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, getCouponByCode, arg.MerchantID, arg.Mode, arg.Code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Code,
		&i.DiscountType,
		&i.Value,
		&i.MaxRedemptions,
		&i.Redemptions,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Mode,
		&i.Status,
	)
	return i, err
}

const listCouponsByMerchant = `-- name: ListCouponsByMerchant :many
SELECT id, merchant_id, code, discount_type, value, max_redemptions, redemptions, expires_at, created_at, mode, status FROM coupons
WHERE merchant_id = $1 AND mode = $2
ORDER BY created_at DESC
`

type ListCouponsByMerchantParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
}

func (q *Queries) ListCouponsByMerchant(ctx context.Context, arg ListCouponsByMerchantParams) ([]Coupon, error) {
	rows, err := q.db.Query(ctx, listCouponsByMerchant, arg.MerchantID, arg.Mode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Coupon{}
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Code,
			&i.DiscountType,
			&i.Value,
			&i.MaxRedemptions,
			&i.Redemptions,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.Mode,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCouponStatus = `-- name: SetCouponStatus :one
UPDATE coupons
SET status = $3
WHERE id = $1 AND merchant_id = $2
RETURNING id, merchant_id, code, discount_type, value, max_redemptions, redemptions, expires_at, created_at, mode, status
`

type SetCouponStatusParams struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
	Status     string    `json:"status"`
}

// Archive (disable) or re-activate a coupon.
func (q *Queries) SetCouponStatus(ctx context.Context, arg SetCouponStatusParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, setCouponStatus, arg.ID, arg.MerchantID, arg.Status)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Code,
		&i.DiscountType,
		&i.Value,
		&i.MaxRedemptions,
		&i.Redemptions,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.Mode,
		&i.Status,
	)
	return i, err
}
