// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: coupons.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCoupon = `-- name: CreateCoupon :one
INSERT INTO coupons (merchant_id, code, discount_type, value, max_redemptions, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, merchant_id, code, discount_type, value, max_redemptions, redemptions, expires_at, created_at
`

type CreateCouponParams struct {
	MerchantID     uuid.UUID   `json:"merchant_id"`
	Code           string      `json:"code"`
	DiscountType   string      `json:"discount_type"`
	Value          int64       `json:"value"`
	MaxRedemptions pgtype.Int4 `json:"max_redemptions"`
	ExpiresAt      *time.Time  `json:"expires_at"`
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, createCoupon,
		arg.MerchantID,
		arg.Code,
		arg.DiscountType,
		arg.Value,
		arg.MaxRedemptions,
		arg.ExpiresAt,
	)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Code,
		&i.DiscountType,
		&i.Value,
		&i.MaxRedemptions,
		&i.Redemptions,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCouponByCode = `-- name: GetCouponByCode :one
SELECT id, merchant_id, code, discount_type, value, max_redemptions, redemptions, expires_at, created_at FROM coupons
WHERE merchant_id = $1 AND code = $2
`

type GetCouponByCodeParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Code       string    `json:"code"`
}

func (q *Queries) GetCouponByCode(ctx context.Context, arg GetCouponByCodeParams) (Coupon, error) {
	row := q.db.QueryRow(ctx, getCouponByCode, arg.MerchantID, arg.Code)
	var i Coupon
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Code,
		&i.DiscountType,
		&i.Value,
		&i.MaxRedemptions,
		&i.Redemptions,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listCouponsByMerchant = `-- name: ListCouponsByMerchant :many
SELECT id, merchant_id, code, discount_type, value, max_redemptions, redemptions, expires_at, created_at FROM coupons
WHERE merchant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListCouponsByMerchant(ctx context.Context, merchantID uuid.UUID) ([]Coupon, error) {
	rows, err := q.db.Query(ctx, listCouponsByMerchant, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Coupon{}
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Code,
			&i.DiscountType,
			&i.Value,
			&i.MaxRedemptions,
			&i.Redemptions,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
