// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (merchant_id, email, name, gateway_customer_ref)
VALUES ($1, $2, $3, $4)
RETURNING id, merchant_id, email, name, gateway_customer_ref, metadata, created_at
`

type CreateCustomerParams struct {
	MerchantID         uuid.UUID   `json:"merchant_id"`
	Email              string      `json:"email"`
	Name               pgtype.Text `json:"name"`
	GatewayCustomerRef pgtype.Text `json:"gateway_customer_ref"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.MerchantID,
		arg.Email,
		arg.Name,
		arg.GatewayCustomerRef,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Email,
		&i.Name,
		&i.GatewayCustomerRef,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const createPaymentMethod = `-- name: CreatePaymentMethod :one
INSERT INTO payment_methods (
    merchant_id, customer_id, gateway_pm_ref, brand, last4, exp_month, exp_year, is_default
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, merchant_id, customer_id, gateway_pm_ref, brand, last4, exp_month, exp_year, is_default, created_at
`

type CreatePaymentMethodParams struct {
	MerchantID   uuid.UUID   `json:"merchant_id"`
	CustomerID   uuid.UUID   `json:"customer_id"`
	GatewayPmRef string      `json:"gateway_pm_ref"`
	Brand        pgtype.Text `json:"brand"`
	Last4        pgtype.Text `json:"last4"`
	ExpMonth     pgtype.Int4 `json:"exp_month"`
	ExpYear      pgtype.Int4 `json:"exp_year"`
	IsDefault    bool        `json:"is_default"`
}

func (q *Queries) CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, createPaymentMethod,
		arg.MerchantID,
		arg.CustomerID,
		arg.GatewayPmRef,
		arg.Brand,
		arg.Last4,
		arg.ExpMonth,
		arg.ExpYear,
		arg.IsDefault,
	)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.GatewayPmRef,
		&i.Brand,
		&i.Last4,
		&i.ExpMonth,
		&i.ExpYear,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getCustomer = `-- name: GetCustomer :one
SELECT id, merchant_id, email, name, gateway_customer_ref, metadata, created_at FROM customers
WHERE id = $1 AND merchant_id = $2
`

type GetCustomerParams struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

func (q *Queries) GetCustomer(ctx context.Context, arg GetCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomer, arg.ID, arg.MerchantID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Email,
		&i.Name,
		&i.GatewayCustomerRef,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getDefaultPaymentMethod = `-- name: GetDefaultPaymentMethod :one
SELECT id, merchant_id, customer_id, gateway_pm_ref, brand, last4, exp_month, exp_year, is_default, created_at FROM payment_methods
WHERE customer_id = $1 AND is_default = true
LIMIT 1
`

func (q *Queries) GetDefaultPaymentMethod(ctx context.Context, customerID uuid.UUID) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, getDefaultPaymentMethod, customerID)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.GatewayPmRef,
		&i.Brand,
		&i.Last4,
		&i.ExpMonth,
		&i.ExpYear,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentMethod = `-- name: GetPaymentMethod :one
SELECT id, merchant_id, customer_id, gateway_pm_ref, brand, last4, exp_month, exp_year, is_default, created_at FROM payment_methods
WHERE id = $1
`

func (q *Queries) GetPaymentMethod(ctx context.Context, id uuid.UUID) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, getPaymentMethod, id)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.GatewayPmRef,
		&i.Brand,
		&i.Last4,
		&i.ExpMonth,
		&i.ExpYear,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const listCustomersByMerchant = `-- name: ListCustomersByMerchant :many
SELECT id, merchant_id, email, name, gateway_customer_ref, metadata, created_at FROM customers
WHERE merchant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCustomersByMerchantParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListCustomersByMerchant(ctx context.Context, arg ListCustomersByMerchantParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomersByMerchant, arg.MerchantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Customer{}
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Email,
			&i.Name,
			&i.GatewayCustomerRef,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCustomerGatewayRef = `-- name: SetCustomerGatewayRef :one
UPDATE customers
SET gateway_customer_ref = $2
WHERE id = $1
RETURNING id, merchant_id, email, name, gateway_customer_ref, metadata, created_at
`

type SetCustomerGatewayRefParams struct {
	ID                 uuid.UUID   `json:"id"`
	GatewayCustomerRef pgtype.Text `json:"gateway_customer_ref"`
}

func (q *Queries) SetCustomerGatewayRef(ctx context.Context, arg SetCustomerGatewayRefParams) (Customer, error) {
	row := q.db.QueryRow(ctx, setCustomerGatewayRef, arg.ID, arg.GatewayCustomerRef)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Email,
		&i.Name,
		&i.GatewayCustomerRef,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
