// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: merchants.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countMerchantsBySubdomain = `-- name: CountMerchantsBySubdomain :one
SELECT COUNT(*)::bigint AS count
FROM merchants WHERE subdomain = $1
`

func (q *Queries) CountMerchantsBySubdomain(ctx context.Context, subdomain string) (int64, error) {
	row := q.db.QueryRow(ctx, countMerchantsBySubdomain, subdomain)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMerchant = `-- name: CreateMerchant :one
INSERT INTO merchants (name, subdomain, owner_name)
VALUES ($1, $2, $3)
RETURNING id, name, status, created_at, updated_at, subdomain, owner_name
`

type CreateMerchantParams struct {
	Name      string `json:"name"`
	Subdomain string `json:"subdomain"`
	OwnerName string `json:"owner_name"`
}

func (q *Queries) CreateMerchant(ctx context.Context, arg CreateMerchantParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, createMerchant, arg.Name, arg.Subdomain, arg.OwnerName)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subdomain,
		&i.OwnerName,
	)
	return i, err
}

const getMerchant = `-- name: GetMerchant :one
SELECT id, name, status, created_at, updated_at, subdomain, owner_name FROM merchants
WHERE id = $1
`

func (q *Queries) GetMerchant(ctx context.Context, id uuid.UUID) (Merchant, error) {
	row := q.db.QueryRow(ctx, getMerchant, id)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subdomain,
		&i.OwnerName,
	)
	return i, err
}

const listMerchants = `-- name: ListMerchants :many
SELECT id, name, status, created_at, updated_at, subdomain, owner_name FROM merchants
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListMerchantsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListMerchants(ctx context.Context, arg ListMerchantsParams) ([]Merchant, error) {
	rows, err := q.db.Query(ctx, listMerchants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Merchant{}
	for rows.Next() {
		var i Merchant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Subdomain,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMerchantStatus = `-- name: UpdateMerchantStatus :one
UPDATE merchants
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, name, status, created_at, updated_at, subdomain, owner_name
`

type UpdateMerchantStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateMerchantStatus(ctx context.Context, arg UpdateMerchantStatusParams) (Merchant, error) {
	row := q.db.QueryRow(ctx, updateMerchantStatus, arg.ID, arg.Status)
	var i Merchant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Subdomain,
		&i.OwnerName,
	)
	return i, err
}
