// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         uuid.UUID          `json:"id"`
	MerchantID uuid.UUID          `json:"merchant_id"`
	Prefix     string             `json:"prefix"`
	KeyHash    string             `json:"key_hash"`
	Scopes     []string           `json:"scopes"`
	LastUsedAt *time.Time         `json:"last_used_at"`
	RevokedAt  *time.Time         `json:"revoked_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type BillingRun struct {
	ID         uuid.UUID          `json:"id"`
	MerchantID uuid.UUID          `json:"merchant_id"`
	Mode       string             `json:"mode"`
	Source     string             `json:"source"`
	Processed  int32              `json:"processed"`
	Succeeded  int32              `json:"succeeded"`
	Failed     int32              `json:"failed"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type CheckoutSession struct {
	ID             uuid.UUID          `json:"id"`
	MerchantID     uuid.UUID          `json:"merchant_id"`
	PriceID        uuid.UUID          `json:"price_id"`
	Quantity       int32              `json:"quantity"`
	Status         string             `json:"status"`
	CustomerEmail  pgtype.Text        `json:"customer_email"`
	SuccessUrl     string             `json:"success_url"`
	CancelUrl      pgtype.Text        `json:"cancel_url"`
	CustomerID     pgtype.UUID        `json:"customer_id"`
	SubscriptionID pgtype.UUID        `json:"subscription_id"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CompletedAt    *time.Time         `json:"completed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Mode           string             `json:"mode"`
}

type CheckoutVisit struct {
	ID         uuid.UUID          `json:"id"`
	MerchantID uuid.UUID          `json:"merchant_id"`
	Mode       string             `json:"mode"`
	SessionID  pgtype.UUID        `json:"session_id"`
	Country    string             `json:"country"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Coupon struct {
	ID             uuid.UUID          `json:"id"`
	MerchantID     uuid.UUID          `json:"merchant_id"`
	Code           string             `json:"code"`
	DiscountType   string             `json:"discount_type"`
	Value          int64              `json:"value"`
	MaxRedemptions pgtype.Int4        `json:"max_redemptions"`
	Redemptions    int32              `json:"redemptions"`
	ExpiresAt      *time.Time         `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Mode           string             `json:"mode"`
	Status         string             `json:"status"`
	ArchivedAt     *time.Time         `json:"archived_at"`
	ArchiveReason  string             `json:"archive_reason"`
}

type Customer struct {
	ID                 uuid.UUID          `json:"id"`
	MerchantID         uuid.UUID          `json:"merchant_id"`
	Email              string             `json:"email"`
	Name               pgtype.Text        `json:"name"`
	GatewayCustomerRef pgtype.Text        `json:"gateway_customer_ref"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	Mode               string             `json:"mode"`
	Country            string             `json:"country"`
}

type DunningAttempt struct {
	ID          uuid.UUID          `json:"id"`
	MerchantID  uuid.UUID          `json:"merchant_id"`
	InvoiceID   uuid.UUID          `json:"invoice_id"`
	AttemptNo   int32              `json:"attempt_no"`
	ScheduledAt pgtype.Timestamptz `json:"scheduled_at"`
	AttemptedAt *time.Time         `json:"attempted_at"`
	Result      pgtype.Text        `json:"result"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Mode        string             `json:"mode"`
}

type Event struct {
	ID         uuid.UUID          `json:"id"`
	MerchantID pgtype.UUID        `json:"merchant_id"`
	Type       string             `json:"type"`
	Payload    []byte             `json:"payload"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type GatewayAccount struct {
	ID                   uuid.UUID          `json:"id"`
	MerchantID           uuid.UUID          `json:"merchant_id"`
	Provider             string             `json:"provider"`
	AccountRef           pgtype.Text        `json:"account_ref"`
	EncryptedCredentials []byte             `json:"encrypted_credentials"`
	Status               string             `json:"status"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	Mode                 string             `json:"mode"`
	PublishableKey       string             `json:"publishable_key"`
}

type Invoice struct {
	ID             uuid.UUID          `json:"id"`
	MerchantID     uuid.UUID          `json:"merchant_id"`
	CustomerID     uuid.UUID          `json:"customer_id"`
	SubscriptionID pgtype.UUID        `json:"subscription_id"`
	Status         string             `json:"status"`
	Currency       string             `json:"currency"`
	SubtotalMinor  int64              `json:"subtotal_minor"`
	DiscountMinor  int64              `json:"discount_minor"`
	TaxMinor       int64              `json:"tax_minor"`
	TotalMinor     int64              `json:"total_minor"`
	PeriodStart    *time.Time         `json:"period_start"`
	PeriodEnd      *time.Time         `json:"period_end"`
	IssuedAt       *time.Time         `json:"issued_at"`
	PaidAt         *time.Time         `json:"paid_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Mode           string             `json:"mode"`
}

type InvoiceLineItem struct {
	ID              uuid.UUID `json:"id"`
	InvoiceID       uuid.UUID `json:"invoice_id"`
	Description     string    `json:"description"`
	Quantity        int32     `json:"quantity"`
	UnitAmountMinor int64     `json:"unit_amount_minor"`
	AmountMinor     int64     `json:"amount_minor"`
}

type Merchant struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Subdomain string             `json:"subdomain"`
	OwnerName string             `json:"owner_name"`
}

type MerchantUser struct {
	ID           uuid.UUID          `json:"id"`
	MerchantID   uuid.UUID          `json:"merchant_id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	Role         string             `json:"role"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type PaymentMethod struct {
	ID           uuid.UUID          `json:"id"`
	MerchantID   uuid.UUID          `json:"merchant_id"`
	CustomerID   uuid.UUID          `json:"customer_id"`
	GatewayPmRef string             `json:"gateway_pm_ref"`
	Brand        pgtype.Text        `json:"brand"`
	Last4        pgtype.Text        `json:"last4"`
	ExpMonth     pgtype.Int4        `json:"exp_month"`
	ExpYear      pgtype.Int4        `json:"exp_year"`
	IsDefault    bool               `json:"is_default"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Mode         string             `json:"mode"`
}

type Price struct {
	ID            uuid.UUID          `json:"id"`
	MerchantID    uuid.UUID          `json:"merchant_id"`
	ProductID     uuid.UUID          `json:"product_id"`
	Nickname      pgtype.Text        `json:"nickname"`
	AmountMinor   int64              `json:"amount_minor"`
	Currency      string             `json:"currency"`
	IntervalUnit  string             `json:"interval_unit"`
	IntervalCount int32              `json:"interval_count"`
	TrialDays     int32              `json:"trial_days"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Mode          string             `json:"mode"`
}

type Product struct {
	ID         uuid.UUID          `json:"id"`
	MerchantID uuid.UUID          `json:"merchant_id"`
	Name       string             `json:"name"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Mode       string             `json:"mode"`
}

type Subscription struct {
	ID                 uuid.UUID          `json:"id"`
	MerchantID         uuid.UUID          `json:"merchant_id"`
	CustomerID         uuid.UUID          `json:"customer_id"`
	PriceID            uuid.UUID          `json:"price_id"`
	PaymentMethodID    pgtype.UUID        `json:"payment_method_id"`
	Status             string             `json:"status"`
	Quantity           int32              `json:"quantity"`
	CurrentPeriodStart *time.Time         `json:"current_period_start"`
	CurrentPeriodEnd   *time.Time         `json:"current_period_end"`
	NextBillingAt      *time.Time         `json:"next_billing_at"`
	CancelAtPeriodEnd  bool               `json:"cancel_at_period_end"`
	CancelledAt        *time.Time         `json:"cancelled_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Mode               string             `json:"mode"`
	CancelReason       string             `json:"cancel_reason"`
}

type Transaction struct {
	ID             uuid.UUID          `json:"id"`
	MerchantID     uuid.UUID          `json:"merchant_id"`
	InvoiceID      pgtype.UUID        `json:"invoice_id"`
	GatewayTxnRef  pgtype.Text        `json:"gateway_txn_ref"`
	Status         string             `json:"status"`
	AmountMinor    int64              `json:"amount_minor"`
	Currency       string             `json:"currency"`
	FailureReason  pgtype.Text        `json:"failure_reason"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	Mode           string             `json:"mode"`
}

type UserMetadatum struct {
	UserID          uuid.UUID          `json:"user_id"`
	TourCompletedAt *time.Time         `json:"tour_completed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type WebhookDelivery struct {
	ID           uuid.UUID          `json:"id"`
	MerchantID   uuid.UUID          `json:"merchant_id"`
	EndpointID   uuid.UUID          `json:"endpoint_id"`
	EventType    string             `json:"event_type"`
	Payload      []byte             `json:"payload"`
	Status       string             `json:"status"`
	Attempts     int32              `json:"attempts"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Mode         string             `json:"mode"`
	ResponseCode pgtype.Int4        `json:"response_code"`
	Error        pgtype.Text        `json:"error"`
}

type WebhookEndpoint struct {
	ID            uuid.UUID          `json:"id"`
	MerchantID    uuid.UUID          `json:"merchant_id"`
	Url           string             `json:"url"`
	SigningSecret string             `json:"signing_secret"`
	Events        []string           `json:"events"`
	Enabled       bool               `json:"enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	Mode          string             `json:"mode"`
	ContentType   string             `json:"content_type"`
	VerifySsl     bool               `json:"verify_ssl"`
}
