// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AdvanceSubscriptionPeriod(ctx context.Context, arg AdvanceSubscriptionPeriodParams) (Subscription, error)
	AnalyticsMRR(ctx context.Context, arg AnalyticsMRRParams) (int64, error)
	CompleteCheckoutSession(ctx context.Context, arg CompleteCheckoutSessionParams) (CheckoutSession, error)
	// Active/trialing subscriptions that existed at a point in time.
	CountActiveSubscriptionsAsOf(ctx context.Context, arg CountActiveSubscriptionsAsOfParams) (int64, error)
	CountCustomers(ctx context.Context, arg CountCustomersParams) (int64, error)
	// Total customers that existed at a point in time (a stock metric).
	CountCustomersAsOf(ctx context.Context, arg CountCustomersAsOfParams) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateCheckoutSession(ctx context.Context, arg CreateCheckoutSessionParams) (CheckoutSession, error)
	CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateDunningAttempt(ctx context.Context, arg CreateDunningAttemptParams) (DunningAttempt, error)
	CreateGatewayAccount(ctx context.Context, arg CreateGatewayAccountParams) (GatewayAccount, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	CreateInvoiceLineItem(ctx context.Context, arg CreateInvoiceLineItemParams) (InvoiceLineItem, error)
	CreateMerchant(ctx context.Context, name string) (Merchant, error)
	CreateMerchantUser(ctx context.Context, arg CreateMerchantUserParams) (MerchantUser, error)
	CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (PaymentMethod, error)
	CreatePrice(ctx context.Context, arg CreatePriceParams) (Price, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error)
	CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error)
	// Disconnect a gateway for a merchant + mode (removes the stored credentials).
	DeleteGatewayAccount(ctx context.Context, arg DeleteGatewayAccountParams) (int64, error)
	DeleteWebhookEndpoint(ctx context.Context, arg DeleteWebhookEndpointParams) error
	GetAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKey, error)
	GetCheckoutSession(ctx context.Context, id uuid.UUID) (CheckoutSession, error)
	// Joined view for the public hosted page: session + plan + merchant + product.
	GetCheckoutSessionDetails(ctx context.Context, id uuid.UUID) (GetCheckoutSessionDetailsRow, error)
	GetCouponByCode(ctx context.Context, arg GetCouponByCodeParams) (Coupon, error)
	GetCustomer(ctx context.Context, arg GetCustomerParams) (Customer, error)
	GetDefaultPaymentMethod(ctx context.Context, customerID uuid.UUID) (PaymentMethod, error)
	GetGatewayAccount(ctx context.Context, arg GetGatewayAccountParams) (GatewayAccount, error)
	GetMerchant(ctx context.Context, id uuid.UUID) (Merchant, error)
	GetMerchantUserByEmail(ctx context.Context, email string) (MerchantUser, error)
	GetPaymentMethod(ctx context.Context, id uuid.UUID) (PaymentMethod, error)
	GetPrice(ctx context.Context, arg GetPriceParams) (Price, error)
	// The merchant's active gateway used for charging, for a given mode.
	GetPrimaryGatewayAccount(ctx context.Context, arg GetPrimaryGatewayAccountParams) (GatewayAccount, error)
	GetSubscription(ctx context.Context, arg GetSubscriptionParams) (Subscription, error)
	ListAPIKeysByMerchant(ctx context.Context, merchantID uuid.UUID) ([]ListAPIKeysByMerchantRow, error)
	ListCouponsByMerchant(ctx context.Context, arg ListCouponsByMerchantParams) ([]Coupon, error)
	ListCustomersByMerchant(ctx context.Context, arg ListCustomersByMerchantParams) ([]Customer, error)
	// The scheduler cursor: subscriptions due for billing now (across all modes).
	ListDueSubscriptions(ctx context.Context, limit int32) ([]Subscription, error)
	// Due subscriptions for one merchant + mode (used by the manual "run now" tool).
	ListDueSubscriptionsForMerchant(ctx context.Context, arg ListDueSubscriptionsForMerchantParams) ([]Subscription, error)
	ListEnabledWebhookEndpoints(ctx context.Context, arg ListEnabledWebhookEndpointsParams) ([]WebhookEndpoint, error)
	ListGatewayAccountsByMerchant(ctx context.Context, arg ListGatewayAccountsByMerchantParams) ([]ListGatewayAccountsByMerchantRow, error)
	ListInvoicesByMerchant(ctx context.Context, arg ListInvoicesByMerchantParams) ([]Invoice, error)
	ListMerchants(ctx context.Context, arg ListMerchantsParams) ([]Merchant, error)
	ListPricesByMerchant(ctx context.Context, arg ListPricesByMerchantParams) ([]Price, error)
	ListProductsByMerchant(ctx context.Context, arg ListProductsByMerchantParams) ([]Product, error)
	ListSubscriptionsByMerchant(ctx context.Context, arg ListSubscriptionsByMerchantParams) ([]Subscription, error)
	ListTransactionsByMerchant(ctx context.Context, arg ListTransactionsByMerchantParams) ([]Transaction, error)
	ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error)
	ListWebhookEndpoints(ctx context.Context, arg ListWebhookEndpointsParams) ([]WebhookEndpoint, error)
	// Recurring revenue from active/trialing subscriptions that existed at a cutoff.
	MRRAsOf(ctx context.Context, arg MRRAsOfParams) (int64, error)
	MarkInvoicePaid(ctx context.Context, id uuid.UUID) (Invoice, error)
	MarkInvoiceStatus(ctx context.Context, arg MarkInvoiceStatusParams) (Invoice, error)
	// Force every active/past_due subscription for a merchant + mode to be due now,
	// so a manual billing run (or the next scheduler tick) will charge them.
	MarkSubscriptionsDueNow(ctx context.Context, arg MarkSubscriptionsDueNowParams) (int64, error)
	// Per-product current MRR vs MRR as of `cutoff` ($3), for growth arrows.
	ProductMRRBreakdown(ctx context.Context, arg ProductMRRBreakdownParams) ([]ProductMRRBreakdownRow, error)
	// ── Period-over-period comparison helpers ──────────────────────────
	// Succeeded revenue inside a [start, end) window (a flow metric).
	RevenueBetween(ctx context.Context, arg RevenueBetweenParams) (int64, error)
	RevenueByDay(ctx context.Context, arg RevenueByDayParams) ([]RevenueByDayRow, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) error
	// Insert a backdated transaction (used by the dev seeder to populate charts).
	SeedTransaction(ctx context.Context, arg SeedTransactionParams) error
	SetCustomerGatewayRef(ctx context.Context, arg SetCustomerGatewayRefParams) (Customer, error)
	SetSubscriptionStatus(ctx context.Context, arg SetSubscriptionStatusParams) (Subscription, error)
	SubscriptionStatusBreakdown(ctx context.Context, arg SubscriptionStatusBreakdownParams) ([]SubscriptionStatusBreakdownRow, error)
	SubscriptionsByDay(ctx context.Context, arg SubscriptionsByDayParams) ([]SubscriptionsByDayRow, error)
	TotalRevenue(ctx context.Context, arg TotalRevenueParams) (int64, error)
	TouchAPIKey(ctx context.Context, id uuid.UUID) error
	UpdateMerchantStatus(ctx context.Context, arg UpdateMerchantStatusParams) (Merchant, error)
	UpdateWebhookDeliveryResult(ctx context.Context, arg UpdateWebhookDeliveryResultParams) (WebhookDelivery, error)
	UpsertGatewayAccount(ctx context.Context, arg UpsertGatewayAccountParams) (UpsertGatewayAccountRow, error)
}

var _ Querier = (*Queries)(nil)
