// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AdvanceSubscriptionPeriod(ctx context.Context, arg AdvanceSubscriptionPeriodParams) (Subscription, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateDunningAttempt(ctx context.Context, arg CreateDunningAttemptParams) (DunningAttempt, error)
	CreateGatewayAccount(ctx context.Context, arg CreateGatewayAccountParams) (GatewayAccount, error)
	CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error)
	CreateInvoiceLineItem(ctx context.Context, arg CreateInvoiceLineItemParams) (InvoiceLineItem, error)
	CreateMerchant(ctx context.Context, name string) (Merchant, error)
	CreateMerchantUser(ctx context.Context, arg CreateMerchantUserParams) (MerchantUser, error)
	CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) (PaymentMethod, error)
	CreatePrice(ctx context.Context, arg CreatePriceParams) (Price, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error)
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	GetAPIKeyByPrefix(ctx context.Context, prefix string) (ApiKey, error)
	GetCustomer(ctx context.Context, arg GetCustomerParams) (Customer, error)
	GetDefaultPaymentMethod(ctx context.Context, customerID uuid.UUID) (PaymentMethod, error)
	GetGatewayAccount(ctx context.Context, arg GetGatewayAccountParams) (GatewayAccount, error)
	GetMerchant(ctx context.Context, id uuid.UUID) (Merchant, error)
	GetMerchantUserByEmail(ctx context.Context, email string) (MerchantUser, error)
	GetPaymentMethod(ctx context.Context, id uuid.UUID) (PaymentMethod, error)
	GetPrice(ctx context.Context, arg GetPriceParams) (Price, error)
	// The merchant's active gateway used for charging (most recently connected).
	GetPrimaryGatewayAccount(ctx context.Context, merchantID uuid.UUID) (GatewayAccount, error)
	GetSubscription(ctx context.Context, arg GetSubscriptionParams) (Subscription, error)
	ListCustomersByMerchant(ctx context.Context, arg ListCustomersByMerchantParams) ([]Customer, error)
	// The scheduler cursor: subscriptions due for billing now.
	ListDueSubscriptions(ctx context.Context, limit int32) ([]Subscription, error)
	ListGatewayAccountsByMerchant(ctx context.Context, merchantID uuid.UUID) ([]ListGatewayAccountsByMerchantRow, error)
	ListMerchants(ctx context.Context, arg ListMerchantsParams) ([]Merchant, error)
	ListPricesByMerchant(ctx context.Context, merchantID uuid.UUID) ([]Price, error)
	ListProductsByMerchant(ctx context.Context, merchantID uuid.UUID) ([]Product, error)
	ListSubscriptionsByMerchant(ctx context.Context, arg ListSubscriptionsByMerchantParams) ([]Subscription, error)
	MarkInvoicePaid(ctx context.Context, id uuid.UUID) (Invoice, error)
	MarkInvoiceStatus(ctx context.Context, arg MarkInvoiceStatusParams) (Invoice, error)
	SetCustomerGatewayRef(ctx context.Context, arg SetCustomerGatewayRefParams) (Customer, error)
	SetSubscriptionStatus(ctx context.Context, arg SetSubscriptionStatusParams) (Subscription, error)
	TouchAPIKey(ctx context.Context, id uuid.UUID) error
	UpdateMerchantStatus(ctx context.Context, arg UpdateMerchantStatusParams) (Merchant, error)
	UpsertGatewayAccount(ctx context.Context, arg UpsertGatewayAccountParams) (UpsertGatewayAccountRow, error)
}

var _ Querier = (*Queries)(nil)
