// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seed.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const seedTransaction = `-- name: SeedTransaction :exec
INSERT INTO transactions (merchant_id, mode, status, amount_minor, currency, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type SeedTransactionParams struct {
	MerchantID  uuid.UUID          `json:"merchant_id"`
	Mode        string             `json:"mode"`
	Status      string             `json:"status"`
	AmountMinor int64              `json:"amount_minor"`
	Currency    string             `json:"currency"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// Insert a backdated transaction (used by the dev seeder to populate charts).
func (q *Queries) SeedTransaction(ctx context.Context, arg SeedTransactionParams) error {
	_, err := q.db.Exec(ctx, seedTransaction,
		arg.MerchantID,
		arg.Mode,
		arg.Status,
		arg.AmountMinor,
		arg.Currency,
		arg.CreatedAt,
	)
	return err
}
