// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscriptions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceSubscriptionPeriod = `-- name: AdvanceSubscriptionPeriod :one
UPDATE subscriptions
SET current_period_start = $2,
    current_period_end = $3,
    next_billing_at = $4,
    status = 'active',
    updated_at = now()
WHERE id = $1
RETURNING id, merchant_id, customer_id, price_id, payment_method_id, status, quantity, current_period_start, current_period_end, next_billing_at, cancel_at_period_end, cancelled_at, created_at, updated_at, mode, cancel_reason
`

type AdvanceSubscriptionPeriodParams struct {
	ID                 uuid.UUID  `json:"id"`
	CurrentPeriodStart *time.Time `json:"current_period_start"`
	CurrentPeriodEnd   *time.Time `json:"current_period_end"`
	NextBillingAt      *time.Time `json:"next_billing_at"`
}

func (q *Queries) AdvanceSubscriptionPeriod(ctx context.Context, arg AdvanceSubscriptionPeriodParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, advanceSubscriptionPeriod,
		arg.ID,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.NextBillingAt,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.PriceID,
		&i.PaymentMethodID,
		&i.Status,
		&i.Quantity,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextBillingAt,
		&i.CancelAtPeriodEnd,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mode,
		&i.CancelReason,
	)
	return i, err
}

const cancelSubscription = `-- name: CancelSubscription :one
UPDATE subscriptions
SET status = 'cancelled',
    cancel_reason = $3,
    cancelled_at = now(),
    next_billing_at = NULL,
    updated_at = now()
WHERE id = $1 AND merchant_id = $2
RETURNING id, merchant_id, customer_id, price_id, payment_method_id, status, quantity, current_period_start, current_period_end, next_billing_at, cancel_at_period_end, cancelled_at, created_at, updated_at, mode, cancel_reason
`

type CancelSubscriptionParams struct {
	ID           uuid.UUID `json:"id"`
	MerchantID   uuid.UUID `json:"merchant_id"`
	CancelReason string    `json:"cancel_reason"`
}

// Cancel a subscription with a reason and stop future billing.
func (q *Queries) CancelSubscription(ctx context.Context, arg CancelSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, cancelSubscription, arg.ID, arg.MerchantID, arg.CancelReason)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.PriceID,
		&i.PaymentMethodID,
		&i.Status,
		&i.Quantity,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextBillingAt,
		&i.CancelAtPeriodEnd,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mode,
		&i.CancelReason,
	)
	return i, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    merchant_id, mode, customer_id, price_id, payment_method_id,
    status, quantity, current_period_start, current_period_end, next_billing_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, merchant_id, customer_id, price_id, payment_method_id, status, quantity, current_period_start, current_period_end, next_billing_at, cancel_at_period_end, cancelled_at, created_at, updated_at, mode, cancel_reason
`

type CreateSubscriptionParams struct {
	MerchantID         uuid.UUID   `json:"merchant_id"`
	Mode               string      `json:"mode"`
	CustomerID         uuid.UUID   `json:"customer_id"`
	PriceID            uuid.UUID   `json:"price_id"`
	PaymentMethodID    pgtype.UUID `json:"payment_method_id"`
	Status             string      `json:"status"`
	Quantity           int32       `json:"quantity"`
	CurrentPeriodStart *time.Time  `json:"current_period_start"`
	CurrentPeriodEnd   *time.Time  `json:"current_period_end"`
	NextBillingAt      *time.Time  `json:"next_billing_at"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.MerchantID,
		arg.Mode,
		arg.CustomerID,
		arg.PriceID,
		arg.PaymentMethodID,
		arg.Status,
		arg.Quantity,
		arg.CurrentPeriodStart,
		arg.CurrentPeriodEnd,
		arg.NextBillingAt,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.PriceID,
		&i.PaymentMethodID,
		&i.Status,
		&i.Quantity,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextBillingAt,
		&i.CancelAtPeriodEnd,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mode,
		&i.CancelReason,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT id, merchant_id, customer_id, price_id, payment_method_id, status, quantity, current_period_start, current_period_end, next_billing_at, cancel_at_period_end, cancelled_at, created_at, updated_at, mode, cancel_reason FROM subscriptions
WHERE id = $1 AND merchant_id = $2
`

type GetSubscriptionParams struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

func (q *Queries) GetSubscription(ctx context.Context, arg GetSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscription, arg.ID, arg.MerchantID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.PriceID,
		&i.PaymentMethodID,
		&i.Status,
		&i.Quantity,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextBillingAt,
		&i.CancelAtPeriodEnd,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mode,
		&i.CancelReason,
	)
	return i, err
}

const insertBillingRun = `-- name: InsertBillingRun :one
INSERT INTO billing_runs (merchant_id, mode, source, processed, succeeded, failed)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, merchant_id, mode, source, processed, succeeded, failed, created_at
`

type InsertBillingRunParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
	Source     string    `json:"source"`
	Processed  int32     `json:"processed"`
	Succeeded  int32     `json:"succeeded"`
	Failed     int32     `json:"failed"`
}

// Record the outcome of a billing pass for the run-history chart.
func (q *Queries) InsertBillingRun(ctx context.Context, arg InsertBillingRunParams) (BillingRun, error) {
	row := q.db.QueryRow(ctx, insertBillingRun,
		arg.MerchantID,
		arg.Mode,
		arg.Source,
		arg.Processed,
		arg.Succeeded,
		arg.Failed,
	)
	var i BillingRun
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Mode,
		&i.Source,
		&i.Processed,
		&i.Succeeded,
		&i.Failed,
		&i.CreatedAt,
	)
	return i, err
}

const listBillingRuns = `-- name: ListBillingRuns :many
SELECT id, merchant_id, mode, source, processed, succeeded, failed, created_at FROM billing_runs
WHERE merchant_id = $1 AND mode = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListBillingRunsParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
	Limit      int32     `json:"limit"`
}

// Recent billing passes for a merchant + mode (newest first).
func (q *Queries) ListBillingRuns(ctx context.Context, arg ListBillingRunsParams) ([]BillingRun, error) {
	rows, err := q.db.Query(ctx, listBillingRuns, arg.MerchantID, arg.Mode, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingRun{}
	for rows.Next() {
		var i BillingRun
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Mode,
			&i.Source,
			&i.Processed,
			&i.Succeeded,
			&i.Failed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueSubscriptions = `-- name: ListDueSubscriptions :many
SELECT id, merchant_id, customer_id, price_id, payment_method_id, status, quantity, current_period_start, current_period_end, next_billing_at, cancel_at_period_end, cancelled_at, created_at, updated_at, mode, cancel_reason FROM subscriptions
WHERE status IN ('active', 'past_due')
  AND next_billing_at IS NOT NULL
  AND next_billing_at <= now()
ORDER BY next_billing_at ASC
LIMIT $1
`

// The scheduler cursor: subscriptions due for billing now (across all modes).
func (q *Queries) ListDueSubscriptions(ctx context.Context, limit int32) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listDueSubscriptions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.CustomerID,
			&i.PriceID,
			&i.PaymentMethodID,
			&i.Status,
			&i.Quantity,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.NextBillingAt,
			&i.CancelAtPeriodEnd,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Mode,
			&i.CancelReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueSubscriptionsForMerchant = `-- name: ListDueSubscriptionsForMerchant :many
SELECT id, merchant_id, customer_id, price_id, payment_method_id, status, quantity, current_period_start, current_period_end, next_billing_at, cancel_at_period_end, cancelled_at, created_at, updated_at, mode, cancel_reason FROM subscriptions
WHERE merchant_id = $1 AND mode = $2
  AND status IN ('active', 'past_due')
  AND next_billing_at IS NOT NULL
  AND next_billing_at <= now()
ORDER BY next_billing_at ASC
LIMIT $3
`

type ListDueSubscriptionsForMerchantParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
	Limit      int32     `json:"limit"`
}

// Due subscriptions for one merchant + mode (used by the manual "run now" tool).
func (q *Queries) ListDueSubscriptionsForMerchant(ctx context.Context, arg ListDueSubscriptionsForMerchantParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listDueSubscriptionsForMerchant, arg.MerchantID, arg.Mode, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.CustomerID,
			&i.PriceID,
			&i.PaymentMethodID,
			&i.Status,
			&i.Quantity,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.NextBillingAt,
			&i.CancelAtPeriodEnd,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Mode,
			&i.CancelReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubscriptionsByMerchant = `-- name: ListSubscriptionsByMerchant :many
SELECT id, merchant_id, customer_id, price_id, payment_method_id, status, quantity, current_period_start, current_period_end, next_billing_at, cancel_at_period_end, cancelled_at, created_at, updated_at, mode, cancel_reason FROM subscriptions
WHERE merchant_id = $1 AND mode = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListSubscriptionsByMerchantParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
	Limit      int32     `json:"limit"`
	Offset     int32     `json:"offset"`
}

func (q *Queries) ListSubscriptionsByMerchant(ctx context.Context, arg ListSubscriptionsByMerchantParams) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptionsByMerchant,
		arg.MerchantID,
		arg.Mode,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Subscription{}
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.CustomerID,
			&i.PriceID,
			&i.PaymentMethodID,
			&i.Status,
			&i.Quantity,
			&i.CurrentPeriodStart,
			&i.CurrentPeriodEnd,
			&i.NextBillingAt,
			&i.CancelAtPeriodEnd,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Mode,
			&i.CancelReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubscriptionsDueNow = `-- name: MarkSubscriptionsDueNow :execrows
UPDATE subscriptions
SET next_billing_at = now(), updated_at = now()
WHERE merchant_id = $1 AND mode = $2 AND status IN ('active', 'past_due')
`

type MarkSubscriptionsDueNowParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
}

// Force every active/past_due subscription for a merchant + mode to be due now,
// so a manual billing run (or the next scheduler tick) will charge them.
func (q *Queries) MarkSubscriptionsDueNow(ctx context.Context, arg MarkSubscriptionsDueNowParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSubscriptionsDueNow, arg.MerchantID, arg.Mode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setSubscriptionStatus = `-- name: SetSubscriptionStatus :one
UPDATE subscriptions
SET status = $2, updated_at = now()
WHERE id = $1 AND merchant_id = $3
RETURNING id, merchant_id, customer_id, price_id, payment_method_id, status, quantity, current_period_start, current_period_end, next_billing_at, cancel_at_period_end, cancelled_at, created_at, updated_at, mode, cancel_reason
`

type SetSubscriptionStatusParams struct {
	ID         uuid.UUID `json:"id"`
	Status     string    `json:"status"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

func (q *Queries) SetSubscriptionStatus(ctx context.Context, arg SetSubscriptionStatusParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, setSubscriptionStatus, arg.ID, arg.Status, arg.MerchantID)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.CustomerID,
		&i.PriceID,
		&i.PaymentMethodID,
		&i.Status,
		&i.Quantity,
		&i.CurrentPeriodStart,
		&i.CurrentPeriodEnd,
		&i.NextBillingAt,
		&i.CancelAtPeriodEnd,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Mode,
		&i.CancelReason,
	)
	return i, err
}
