// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getUserMetadata = `-- name: GetUserMetadata :one
SELECT user_id, tour_completed_at, created_at, updated_at
FROM user_metadata
WHERE user_id = $1
`

func (q *Queries) GetUserMetadata(ctx context.Context, userID uuid.UUID) (UserMetadatum, error) {
	row := q.db.QueryRow(ctx, getUserMetadata, userID)
	var i UserMetadatum
	err := row.Scan(
		&i.UserID,
		&i.TourCompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markTourCompleted = `-- name: MarkTourCompleted :exec
INSERT INTO user_metadata (user_id, tour_completed_at)
VALUES ($1, now())
ON CONFLICT (user_id)
DO UPDATE SET tour_completed_at = now(), updated_at = now()
`

func (q *Queries) MarkTourCompleted(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, markTourCompleted, userID)
	return err
}
