// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :one
INSERT INTO webhook_endpoints (merchant_id, url, signing_secret, events, enabled)
VALUES ($1, $2, $3, $4, true)
RETURNING id, merchant_id, url, signing_secret, events, enabled, created_at
`

type CreateWebhookEndpointParams struct {
	MerchantID    uuid.UUID `json:"merchant_id"`
	Url           string    `json:"url"`
	SigningSecret string    `json:"signing_secret"`
	Events        []string  `json:"events"`
}

func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, createWebhookEndpoint,
		arg.MerchantID,
		arg.Url,
		arg.SigningSecret,
		arg.Events,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Url,
		&i.SigningSecret,
		&i.Events,
		&i.Enabled,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWebhookEndpoint = `-- name: DeleteWebhookEndpoint :exec
DELETE FROM webhook_endpoints
WHERE id = $1 AND merchant_id = $2
`

type DeleteWebhookEndpointParams struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

func (q *Queries) DeleteWebhookEndpoint(ctx context.Context, arg DeleteWebhookEndpointParams) error {
	_, err := q.db.Exec(ctx, deleteWebhookEndpoint, arg.ID, arg.MerchantID)
	return err
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, merchant_id, endpoint_id, event_type, payload, status, attempts, created_at FROM webhook_deliveries
WHERE merchant_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListWebhookDeliveriesParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Limit      int32     `json:"limit"`
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries, arg.MerchantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.EndpointID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpoints = `-- name: ListWebhookEndpoints :many
SELECT id, merchant_id, url, signing_secret, events, enabled, created_at FROM webhook_endpoints
WHERE merchant_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWebhookEndpoints(ctx context.Context, merchantID uuid.UUID) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpoints, merchantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Url,
			&i.SigningSecret,
			&i.Events,
			&i.Enabled,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
