// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (merchant_id, mode, endpoint_id, event_type, payload, status, attempts)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, merchant_id, endpoint_id, event_type, payload, status, attempts, created_at, mode
`

type CreateWebhookDeliveryParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
	EndpointID uuid.UUID `json:"endpoint_id"`
	EventType  string    `json:"event_type"`
	Payload    []byte    `json:"payload"`
	Status     string    `json:"status"`
	Attempts   int32     `json:"attempts"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.MerchantID,
		arg.Mode,
		arg.EndpointID,
		arg.EventType,
		arg.Payload,
		arg.Status,
		arg.Attempts,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.EndpointID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.Mode,
	)
	return i, err
}

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :one
INSERT INTO webhook_endpoints (merchant_id, mode, url, signing_secret, events, enabled)
VALUES ($1, $2, $3, $4, $5, true)
RETURNING id, merchant_id, url, signing_secret, events, enabled, created_at, mode
`

type CreateWebhookEndpointParams struct {
	MerchantID    uuid.UUID `json:"merchant_id"`
	Mode          string    `json:"mode"`
	Url           string    `json:"url"`
	SigningSecret string    `json:"signing_secret"`
	Events        []string  `json:"events"`
}

func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, createWebhookEndpoint,
		arg.MerchantID,
		arg.Mode,
		arg.Url,
		arg.SigningSecret,
		arg.Events,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Url,
		&i.SigningSecret,
		&i.Events,
		&i.Enabled,
		&i.CreatedAt,
		&i.Mode,
	)
	return i, err
}

const deleteWebhookEndpoint = `-- name: DeleteWebhookEndpoint :exec
DELETE FROM webhook_endpoints
WHERE id = $1 AND merchant_id = $2
`

type DeleteWebhookEndpointParams struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

func (q *Queries) DeleteWebhookEndpoint(ctx context.Context, arg DeleteWebhookEndpointParams) error {
	_, err := q.db.Exec(ctx, deleteWebhookEndpoint, arg.ID, arg.MerchantID)
	return err
}

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT id, merchant_id, endpoint_id, event_type, payload, status, attempts, created_at, mode FROM webhook_deliveries
WHERE id = $1 AND merchant_id = $2
`

type GetWebhookDeliveryParams struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

func (q *Queries) GetWebhookDelivery(ctx context.Context, arg GetWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDelivery, arg.ID, arg.MerchantID)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.EndpointID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.Mode,
	)
	return i, err
}

const getWebhookEndpoint = `-- name: GetWebhookEndpoint :one
SELECT id, merchant_id, url, signing_secret, events, enabled, created_at, mode FROM webhook_endpoints
WHERE id = $1 AND merchant_id = $2
`

type GetWebhookEndpointParams struct {
	ID         uuid.UUID `json:"id"`
	MerchantID uuid.UUID `json:"merchant_id"`
}

func (q *Queries) GetWebhookEndpoint(ctx context.Context, arg GetWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpoint, arg.ID, arg.MerchantID)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.Url,
		&i.SigningSecret,
		&i.Events,
		&i.Enabled,
		&i.CreatedAt,
		&i.Mode,
	)
	return i, err
}

const listEnabledWebhookEndpoints = `-- name: ListEnabledWebhookEndpoints :many
SELECT id, merchant_id, url, signing_secret, events, enabled, created_at, mode FROM webhook_endpoints
WHERE merchant_id = $1 AND mode = $2 AND enabled = true
`

type ListEnabledWebhookEndpointsParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
}

func (q *Queries) ListEnabledWebhookEndpoints(ctx context.Context, arg ListEnabledWebhookEndpointsParams) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listEnabledWebhookEndpoints, arg.MerchantID, arg.Mode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Url,
			&i.SigningSecret,
			&i.Events,
			&i.Enabled,
			&i.CreatedAt,
			&i.Mode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, merchant_id, endpoint_id, event_type, payload, status, attempts, created_at, mode FROM webhook_deliveries
WHERE merchant_id = $1 AND mode = $2
ORDER BY created_at DESC
LIMIT $3
`

type ListWebhookDeliveriesParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
	Limit      int32     `json:"limit"`
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries, arg.MerchantID, arg.Mode, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.EndpointID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.CreatedAt,
			&i.Mode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpoints = `-- name: ListWebhookEndpoints :many
SELECT id, merchant_id, url, signing_secret, events, enabled, created_at, mode FROM webhook_endpoints
WHERE merchant_id = $1 AND mode = $2
ORDER BY created_at DESC
`

type ListWebhookEndpointsParams struct {
	MerchantID uuid.UUID `json:"merchant_id"`
	Mode       string    `json:"mode"`
}

func (q *Queries) ListWebhookEndpoints(ctx context.Context, arg ListWebhookEndpointsParams) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpoints, arg.MerchantID, arg.Mode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.MerchantID,
			&i.Url,
			&i.SigningSecret,
			&i.Events,
			&i.Enabled,
			&i.CreatedAt,
			&i.Mode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhookDeliveryResult = `-- name: UpdateWebhookDeliveryResult :one
UPDATE webhook_deliveries
SET status = $2, attempts = $3
WHERE id = $1
RETURNING id, merchant_id, endpoint_id, event_type, payload, status, attempts, created_at, mode
`

type UpdateWebhookDeliveryResultParams struct {
	ID       uuid.UUID `json:"id"`
	Status   string    `json:"status"`
	Attempts int32     `json:"attempts"`
}

func (q *Queries) UpdateWebhookDeliveryResult(ctx context.Context, arg UpdateWebhookDeliveryResultParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, updateWebhookDeliveryResult, arg.ID, arg.Status, arg.Attempts)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.MerchantID,
		&i.EndpointID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.CreatedAt,
		&i.Mode,
	)
	return i, err
}
